server:
	python3 serv4.py
	@echo "Ejecutando el servidor..."

client:
	python3 cli4.py
	@echo "Ejecutando el cliente..."


all:
	@echo "Compilación y ejecución de la práctica"

clean:
	@echo "Limpiando..."
